Caffe2 build failed

diff --git a/tests/Dockerfile b/tests/Dockerfile
--- a/tests/Dockerfile
+++ b/tests/Dockerfile
@@ -3,16 +3,81 @@ FROM ubuntu:trusty
 MAINTAINER Shunta Saito <shunta.saito@gmail.com>
 
 RUN apt-get update
-RUN apt-get install -y build-essential git wget
+RUN apt-get install -y build-essential git wget cmake
+RUN apt-get install -y \
+    asciidoc \
+    autoconf \
+    automake \
+    build-essential \
+    ca-certificates \
+    ccache \
+    docbook-xml \
+    docbook-xsl \
+    git \
+    gperf \
+    libatlas-base-dev \
+    libgoogle-glog-dev \
+    libiomp-dev \
+    libleveldb-dev \
+    liblmdb-dev \
+    libopencv-dev \
+    libprotobuf-dev \
+    libpthread-stubs0-dev \
+    libsnappy-dev \
+    protobuf-compiler \
+    software-properties-common \
+    xsltproc
+
 RUN wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh
-RUN bash miniconda.sh -b -p $HOME/miniconda
-RUN export PATH="$HOME/miniconda/bin:$PATH"
-RUN hash -r
+RUN bash miniconda.sh -b -p miniconda
+ENV PATH /miniconda/bin:$PATH
+
 RUN conda config --set always_yes yes --set changeps1 no
-RUN conda info -a
-RUN conda install protobuf
-RUN conda install glog
-RUN hash -r
-RUN CFLAGS="-I$HOME/miniconda/include" pip install git+git://github.com/onnx/onnx.git@a8bd1facd321ea52f0a6f88600138606711b7a96
+
 RUN pip install chainer==3.1.0
-RUN pip install -e .
+RUN pip install future
+RUN pip install hypothesis
+RUN pip install numpy
+RUN pip install flake8
+RUN pip install hacking
+RUN pip install autopep8
+RUN pip install mock
+RUN pip install pytest
+RUN pip install six
+
+RUN CFLAGS="-I/miniconda/include" \
+    pip install git+git://github.com/onnx/onnx.git@a8bd1facd321ea52f0a6f88600138606711b7a96
+ENV LD_LIBRARY_PATH /miniconda/lib:$LD_LIBRARY_PATH
+
+RUN git clone --recursive https://github.com/caffe2/caffe2.git
+RUN cd caffe2 && mkdir build && cd build \
+    && cmake .. \
+    -DUSE_CUDA=OFF \
+    -DUSE_NCCL=OFF \
+    -DUSE_NNPACK=OFF \
+    -DUSE_ROCKSDB=OFF \
+    -DUSE_LEVELDB=OFF \
+    -DUSE_LMDB=OFF \
+    -DUSE_LITE_PROTO=ON \
+    -DUSE_OPENCV=OFF \
+    -DCMAKE_CXX_FLAGS="-v" \
+    -DCMAKE_C_FLAGS="-v" \
+    -DPYTHON_INCLUDE_DIR=/miniconda/include \
+    -DPYTHON_INCLUDE_DIR2=/miniconda/include/python3.6m \
+    -DPYTHON_LIBRARY=/miniconda/lib/libpython3.6m.so \
+    -DPYTHON_LIBRARY_DEBUG=/miniconda/lib/libpython3.6m.so \
+    -DPROTOBUF_INCLUDE_DIR=/miniconda/include \
+    -DPROTOBUF_LIBRARY=/miniconda/lib/libprotobuf.so \
+    -DPROTOBUF_LIBRARY_DEBUG=/miniconda/lib/libprotobuf.so \
+    -DPROTOBUF_LITE_LIBRARY=/miniconda/lib/libprotobuf-lite.so \
+    -DPROTOBUF_LITE_LIBRARY_DEBUG=/miniconda/lib/libprotobuf-lite.so \
+    -DPROTOBUF_PROTOC_LIBRARY=/miniconda/lib/libprotoc.so \
+    -DPROTOBUF_PROTOC_LIBRARY_DEBUG=/miniconda/lib/libprotoc.so \
+    -Dpybind11_INCLUDE_DIR=/miniconda/include/python3.6m/pybind11 \
+    && make -j"$(nproc)" install \
+    && ldconfig \
+    && make clean \
+    && cd .. \
+    && rm -rf build
+ENV PYTHONPATH /usr/local/
+RUN python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
